### ISSUE TITLE
Small bug in records.go

### ISSUE THREAD

**Issue by yoav-orca** [C-Sto/gosecretsdump#15]
I wanted to switch to use `gosecretsdump` and I have a script that parses the output for impact, I found a small bug:
https://github.com/C-Sto/gosecretsdump/blob/d6ea835883f943779a21bbc0c3cd6e05b1634bf9/pkg/ditreader/records.go#L85

It should be `err == nil` and not `err != nil`

**Comment by C-Sto** [comment]
well spotted!
